server:
  port: 8020
spring:
  application:
    name: menu
  datasource:
    url: jdbc:mysql://localhost:3306/orderingsystem?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: mafeng_1234_
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    root: info
    com.lea: debug
mybatis-plus:
  mapper-locations: classpath:/mybatis-mappers/*
  type-aliases-package: com.lea.entity